# Wind data EDA

## Loading packages

In [14]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
import seaborn as sns

## Importing data

In [15]:
df_weather = pd.read_csv('../data/Weather/WeatherDataCleaned.csv')
df_weather

,Datetime,Station,WindDirection,WindSpeedAvg60min,WindSpeedAvg10min,WindGust,Temperature,DewPoint,Sunshineperhour,GlobalRadiation,...,CloudCover,RelativeAtmosphericHumidity,IndicatorWeatherCode,Fog,Rain,Snow,Thunder,IceFormation,AvgDailyTemperature,TemperatureAvgMonthlyTemperature
0,2021-01-01 00:00:00,260,230,10,10,20,-2.5,-26,0,0,...,0,98,7,1,0,0,0,1,2.970833,3.376747
1,2021-01-01 01:00:00,260,230,10,10,20,-3.2,-34,0,0,...,1,98,7,1,0,0,0,1,2.970833,3.376747
2,2021-01-01 02:00:00,260,230,20,20,30,-2.7,-29,0,0,...,7,98,7,1,0,0,0,1,2.970833,3.376747
3,2021-01-01 03:00:00,260,220,20,20,30,-1.1,-14,0,0,...,8,98,7,1,0,0,0,1,2.970833,3.376747
4,2021-01-01 04:00:00,260,230,20,20,40,1.1,5,0,0,...,8,95,7,0,0,0,0,0,2.970833,3.376747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26275,2023-12-31 19:00:00,260,200,80,70,140,8.6,50,0,0,...,8,77,7,0,1,0,0,0,8.829167,6.888441
26276,2023-12-31 20:00:00,260,200,70,70,150,8.2,56,0,0,...,8,84,7,0,1,0,0,0,8.829167,6.888441
26277,2023-12-31 21:00:00,260,200,70,70,140,8.1,56,0,0,...,8,84,7,0,1,0,0,0,8.829167,6.888441
26278,2023-12-31 22:00:00,260,210,80,80,150,8.6,50,0,0,...,8,78,7,0,1,0,0,0,8.829167,6.888441
26279,2023-12-31 23:00:00,260,210,80,80,150,8.2,44,0,0,...,8,77,7,0,1,0,0,0,8.829167,6.888441

In [25]:
df_windmills = pd.read_csv('../data/Other/Windmolens_2021-2023.csv',sep=';', skiprows=3)
df_windmills

,Onderwerp,Windmolens|Opgestelde windmolens einde van jaar,Windmolens|Opgestelde windmolens einde van jaar.1,Windmolens|Opgestelde windmolens einde van jaar.2,Elektrisch vermogen|Opgesteld vermogen einde jaar,Elektrisch vermogen|Opgesteld vermogen einde jaar.1,Elektrisch vermogen|Opgesteld vermogen einde jaar.2,Elektriciteitsproductie|Niet-genormaliseerde productie,Elektriciteitsproductie|Niet-genormaliseerde productie.1,Elektriciteitsproductie|Niet-genormaliseerde productie.2,Elektriciteitsproductie|Productiefactor,Elektriciteitsproductie|Productiefactor.1,Elektriciteitsproductie|Productiefactor.2
0,Perioden,2021,2022,2023**,2021,2022,2023**,2021,2022,2023**,2021,2022,2023**
1,Regio's,aantal,aantal,aantal,megawatt,megawatt,megawatt,mln kWh,mln kWh,mln kWh,%,%,%
2,Nederland,2308,2446,2557,5186,6131,6757,10058,13440,17814,"24,2","27,3","31,5"
3,Groningen (PV),262,284,290,731,839,868,1563,2043,2315,"25,6","29,1","31,2"
4,Fryslân (PV),368,370,370,576,619,619,946,1679,1915,"23,2","32,3","35,3"
5,Drenthe (PV),61,68,75,221,246,271,207,643,786,"16,9","32,9","33,0"
6,Overijssel (PV),29,29,32,74,74,87,135,155,188,"22,3","23,7","27,2"
7,Flevoland (PV),613,627,689,1285,1584,1992,2285,3043,4570,"22,1","24,0","29,6"
8,Gelderland (PV),61,78,81,171,234,247,361,455,624,"25,2","23,7","29,6"
9,Utrecht (PV),16,16,16,34,34,34,73,78,94,"24,3","26,3","31,3"
10,Noord-Holland (PV),316,330,329,652,700,700,1631,1855,2072,"28,6","30,7","33,8"
11,Zuid-Holland (PV),185,224,226,520,767,775,1061,1363,2208,"24,0","26,4","32,8"
12,Zeeland (PV),243,248,258,549,566,611,1174,1295,1656,"25,8","26,2","31,5"
13,Noord-Brabant (PV),135,144,160,301,353,428,541,616,1055,"22,9","23,1","28,9"
14,Limburg (PV),19,28,31,72,114,125,80,215,331,"21,6","27,2","30,5"
15,Bron: CBS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df_production = pd.read_csv('../data/ProductionData/cleaned_energie_opwek.csv')
df_production

,datetime,point,type,granularity,timezone,activity,classification,capacity,volume,percentage,emission,emissionfactor
0,2020-12-31 23:00:00,Nederland,WastePower,Hour,UTC,Providing,Current,418750,418750,0.536859,125625,0.3
1,2021-01-01 00:00:00,Nederland,WastePower,Hour,UTC,Providing,Current,416000,416000,0.533333,124800,0.3
2,2021-01-01 01:00:00,Nederland,WastePower,Hour,UTC,Providing,Current,430250,430250,0.551602,129075,0.3
3,2021-01-01 02:00:00,Nederland,WastePower,Hour,UTC,Providing,Current,436750,436750,0.559936,131025,0.3
4,2021-01-01 03:00:00,Nederland,WastePower,Hour,UTC,Providing,Current,436000,436000,0.558974,130800,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...
271579,2023-12-31 18:00:00,Nederland,WindOffshoreC,Hour,UTC,Providing,Current,3144000,3144000,1.431400,0,0.0
271580,2023-12-31 19:00:00,Nederland,WindOffshoreC,Hour,UTC,Providing,Current,3102250,3102250,1.412392,0,0.0
271581,2023-12-31 20:00:00,Nederland,WindOffshoreC,Hour,UTC,Providing,Current,3086249,3086249,1.405107,0,0.0
271582,2023-12-31 21:00:00,Nederland,WindOffshoreC,Hour,UTC,Providing,Current,3051749,3051749,1.389403,0,0.0
271583,2023-12-31 22:00:00,Nederland,WindOffshoreC,Hour,UTC,Providing,Current,3074000,3074000,1.399530,0,0.0