In [20]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt 
import seaborn as sns

pd.set_option('display.max_columns', None)

In [21]:
df = pd.read_csv('../data/Weather/WeatherData.txt',skiprows=31, sep=',')
df

,# STN,YYYYMMDD,HH,DD,FH,FF,FX,T,T10N,TD,SQ,Q,DR,RH,P,VV,N,U,WW,IX,M,R,S,O,Y
0,260,20210101,1,230,10,10,20,-25,,-26,0,0,0,0,10059,1,0,98,35,7,1,0,0,0,1
1,260,20210101,2,230,10,10,20,-32,,-34,0,0,0,0,10061,0,1,98,35,7,1,0,0,0,1
2,260,20210101,3,230,20,20,30,-27,,-29,0,0,0,0,10064,4,7,98,35,7,1,0,0,0,1
3,260,20210101,4,220,20,20,30,-11,,-14,0,0,0,0,10064,15,8,98,20,7,1,0,0,0,1
4,260,20210101,5,230,20,20,40,11,,5,0,0,0,0,10064,18,8,95,10,7,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26275,260,20231231,20,200,80,70,140,86,,50,0,0,0,-1,9951,75,8,77,81,7,0,1,0,0,0
26276,260,20231231,21,200,70,70,150,82,,56,0,0,0,-1,9954,70,8,84,81,7,0,1,0,0,0
26277,260,20231231,22,200,70,70,140,81,,56,0,0,3,2,9955,70,8,84,81,7,0,1,0,0,0
26278,260,20231231,23,210,80,80,150,86,,50,0,0,0,-1,9959,75,8,78,23,7,0,1,0,0,0
26279,260,20231231,24,210,80,80,150,82,70,44,0,0,0,-1,9962,67,8,77,51,7,0,1,0,0,0

In [ ]:
# New column names
new_column_names = [
    "Station", "Date", "Hour", "WindDirection", "WindSpeedAvg10min", "WindSpeedAvg",
    "WindSpeedGust", "Temperature", "MinTemperature10min", "DewPoint", "Sunshine",
    "GlobalRadiation", "PrecipitationDuration", "HourlyPrecipitationAmount", "Pressure",
    "Visibility", "CloudCover", "RelativeAtmosphericHumidity", "WeatherCode", "Index", "Mist", 
    "Rain", "Snow", "Thunder", "Storm"
]

# Rename columns
df.columns = new_column_names

In [23]:
df

,Station,Date,Hour,WindDirection,WindSpeedAvg10min,WindSpeedAvg,WindSpeedGust,Temperature,MinTemperature10min,DewPoint,Sunshine,GlobalRadiation,PrecipitationDuration,RelativeHumidity,Pressure,Visibility,CloudCover,RelativeAtmosphericHumidity,WeatherCode,Index,Mist,Rain,Snow,Other,Storm
0,260,20210101,1,230,10,10,20,-25,,-26,0,0,0,0,10059,1,0,98,35,7,1,0,0,0,1
1,260,20210101,2,230,10,10,20,-32,,-34,0,0,0,0,10061,0,1,98,35,7,1,0,0,0,1
2,260,20210101,3,230,20,20,30,-27,,-29,0,0,0,0,10064,4,7,98,35,7,1,0,0,0,1
3,260,20210101,4,220,20,20,30,-11,,-14,0,0,0,0,10064,15,8,98,20,7,1,0,0,0,1
4,260,20210101,5,230,20,20,40,11,,5,0,0,0,0,10064,18,8,95,10,7,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26275,260,20231231,20,200,80,70,140,86,,50,0,0,0,-1,9951,75,8,77,81,7,0,1,0,0,0
26276,260,20231231,21,200,70,70,150,82,,56,0,0,0,-1,9954,70,8,84,81,7,0,1,0,0,0
26277,260,20231231,22,200,70,70,140,81,,56,0,0,3,2,9955,70,8,84,81,7,0,1,0,0,0
26278,260,20231231,23,210,80,80,150,86,,50,0,0,0,-1,9959,75,8,78,23,7,0,1,0,0,0
26279,260,20231231,24,210,80,80,150,82,70,44,0,0,0,-1,9962,67,8,77,51,7,0,1,0,0,0

help